---
- name: ensure deja-dup is installed
  apt: name=deja-dup state=installed

- name: ensure python-boto is installed
  apt: name=python-boto state=installed

#FIXME: dconf-WARNING **: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY
- name: configure deja-dup
  command: gsettings set org.gnome.DejaDup {{ item.key }} {{ item.value }}
  with_dict: "{{ dejadup.root }}"

#FIXME: dconf-WARNING **: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY
- name: configure deja-dup s3 backend
  command: gsettings set org.gnome.DejaDup.S3 {{ item.key }} {{ item.value }}
  with_dict: "{{ dejadup.s3 }}"
