---
- name: ensure deja-dup is installed
  apt: name=deja-dup state=installed

- name: ensure python-boto is installed
  apt: name=python-boto state=installed

- name: start dbus
  command: dbus-launch --exit-with-session true
  become_user: "{{ my_user }}"

- name: configure deja-dup
  command: gsettings set org.gnome.DejaDup {{ item.key }} {{ item.value }}
  with_dict: "{{ dejadup.root }}"
  become_user: "{{ my_user }}"

- name: configure deja-dup s3 backend
  command: gsettings set org.gnome.DejaDup.S3 {{ item.key }} {{ item.value }}
  with_dict: "{{ dejadup.s3 }}"
  become_user: "{{ my_user }}"

- name: stop dbus
  shell: kill -15 $(ps -fu {{ my_user }} | awk '/dbus-launch --exit-with-session true/ && !/grep/ {print $2}')
  become_user: "{{ my_user }}"
