---
- name: ensure keepassx repository is installed
  apt_repository: repo='ppa:keepassx/daily' filename=keepassx update_cache=yes mode=644

- name: ensure keepassx is at the latest version
  apt: name=keepassx state=latest
