---
- name: ensure tools are installed
  apt: name={{ item }}
  with_items:
  - exfat-fuse
  - exfat-utils
  - hfsprogs
  - redshift-gtk

- include: keepassx.yml
- include: owncloud-client.yml
- include: backup.yml
  when: dejadup_all.state
- include: ssd.yml
  when: ssd
