---
- name: ensure docker package for raspbian is downloaded
  get_url: url={{ docker_raspbian_url }} dest={{ ansible_cache }}/{{ docker_raspbian_package }}

- name: ensure docker is installed
  apt: deb={{ ansible_cache }}/{{ docker_raspbian_package }}

- name: ensure docker is running (and enable it at boot)
  service: name=docker state=started enabled=yes

- name: ensure docker group exists
  group: name=docker state=present

- name: ensure user is part of docker group
  user: name={{ my_user }} groups=docker append=yes

- name: ensure docker environment file exists
  copy: dest=/home/{{ my_user }}/.environment.d/40docker.sh src="files/env_40docker.sh"
          mode=0755 owner={{ my_user }}
