---
- include: x86_64.yml
  when: ansible_architecture == "x86_64"

- include: armv7.yml
  when: ansible_architecture == "armv7l"

- name: ensure docker is running (and enable it at boot)
  service: name=docker state=started enabled=yes

- name: ensure docker group exists
  group: name=docker state=present

- name: ensure user is part of docker group
  user: name={{ my_user }} groups=docker append=yes

- name: ensure pip is installed
  apt: name=python-pip state=latest

- name: ensure docker-compose is installed
  pip: name=docker-compose state=latest

- name: ensure docker environment file exists
  copy: dest=/home/{{ my_user }}/.environment.d/40docker.sh src="files/env_40docker.sh"
          mode=0755 owner={{ my_user }}
