---
docker_repo: https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main
docker_raspbian_url: https://downloads.hypriot.com/{{ docker_raspbian_package }}
docker_raspbian_package: docker-hypriot_1.10.3-1_armhf.deb
