---
# tasks file for common

- name: ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: ensure common packages are installed
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ common_packages }}"

- name: ensure vim is the default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- include: user.yml

- include: ssh.yml
