---
- name: ensure user exists
  user: name={{ my_user }} password="{{ lookup('file','files/private-{{ my_user }}.passwd') }}" shell=/usr/bin/zsh

- name: ensure ssh public key is deployed
  authorized_key: user={{ my_user }} key="{{ lookup('file','files/private-{{ my_user }}.pub') }}"

- name: ensure user can do sudo commands
  lineinfile: dest=/etc/sudoers state=present regexp='^{{ my_user }} ALL\=' line='{{ my_user }} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: ensure SSH user connection is enabled
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp='AllowUsers {{ my_user }}' line='AllowUsers {{ my_user }}'
  notify: restart ssh

- name: ensure apps directory exists
  file: path=/home/{{ my_user }}/.apps state=directory mode=0755 owner={{ my_user }}

- name: ensure environment directory exists
  file: path=/home/{{ my_user }}/.environment.d state=directory mode=0755 owner={{ my_user }}

- name: ensure environment files exist
  copy: dest=/home/{{ my_user }}/.environment.d/{{ item }}.sh src="files/env_{{ item }}.sh"
          mode=0755 owner={{ my_user }} group={{ my_group }}
  with_items:
    - 10debian
    - 90others
    - 40git
    - 10shell
