---
- name: ensure atom package is downloaded
  get_url: url={{ atom_url }} dest={{ ansible_cache }}/{{ atom_package }}
  become_user: "{{ ansible_user }}"

- name: ensure atom is installed
  apt: deb={{ ansible_cache }}/{{ atom_package }}

- include: apm.yml package=language-ansible
- include: apm.yml package=language-diff
- include: apm.yml package=language-docker
- include: apm.yml package=split-diff
