---
- name: ensure apt can work with https
  apt: name=apt-transport-https

- name: ensure ca certificates are installed
  apt: name=ca-certificates

- name: ensure docker apt-key is installed
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: ensure docker repository is installed
  apt_repository: repo='deb {{ docker_repo }}' filename=docker update_cache=yes mode=644

- name: ensure that apt is pulling from the right repository
  command: apt-cache policy docker-engine

- name: ensure docker is at the latest version
  apt: name=docker-engine state=latest

- name: ensure docker is running (and enable it at boot)
  service: name=docker state=started enabled=yes

- name: ensure docker group exists
  group: name=docker state=present

- name: ensure user is part of docker group
  user: name={{ ansible_user }} groups=docker append=yes

- name: ensure docker-compose is installed
  get_url: url={{ compose_url }} dest=/usr/local/bin/docker-compose

- name: ensure docker environment file exists
  copy: dest=/home/{{ user }}/.environment.d/40docker.sh src="files/env_40docker.sh"
          mode=0755 owner={{ user }} group={{ ansible_group }}
