---
- name: ensure apps directory exists
  file: path=/home/{{ user }}/.apps state=directory mode=0755 owner={{ user }} group={{ ansible_group }}

- name: ensure environment directory exists
  file: path=/home/{{ user }}/.environment.d state=directory mode=0755 owner={{ user }} group={{ ansible_group }}

- name: ensure environment files exist
  copy: dest=/home/{{ user }}/.environment.d/{{ item }}.sh src="files/env_{{ item }}.sh"
          mode=0755 owner={{ user }} group={{ ansible_group }}
  with_items:
    - 20python
    - 40docker
