---
- name: ensure dev tools are installed
  apt: name={{ item }}
  with_items:
  - build-essential
  - git
  - git-cola

- include: python.yml user={{ ansible_user }}
- include: atom.yml
- include: docker.yml user={{ ansible_user }}
