---
- name: ensure dev tools are installed
  apt: name={{ item }}
  with_items:
  - build-essential
  - git
  - git-cola
  - meld
  - shellcheck

- include: python.yml
- include: ansible.yml
- include: atom.yml
- include: docker.yml
