---
- name: ensure ufw is at the latest version
  apt: name=ufw state=latest

- name: ensure ufw is started with deny all default policy
  ufw: state=enabled policy=deny

- name: ensure ssh is allowed
  ufw: rule=allow port=22 proto=tcp

- name: ensure http is allowed
  ufw: rule=allow port=80 proto=tcp

- name: ensure https is allowed
  ufw: rule=allow port=443 proto=tcp
